### ISSUE TITLE
Alt + up/down should emulate control + a / control + e

### ISSUE THREAD

**Issue by alexellis** [rosston/sublime-word-navigation-atom#1]
This is my second biggest gripe after moving to Atom - (1st is the lag) - alt + up/down should emulate control + a / control + e.

Do you cover this in your 'word navigation' plugin?

**Comment by rosston** [comment]
No, this plugin doesn't fix alt + up/down. I didn't actually know about those shortcuts until now.

I don't think I want to set alt + up/down in this plugin's keymap though. That shortcut seems too likely for other plugins to override. Looking at my plugins, both [emmet](https://atom.io/packages/emmet) and [line-jumper](https://atom.io/packages/line-jumper) use alt + up/down.

But! You can fix the shortcuts in your own keymap. Just put in the code below (sublime-word-navigation not required):

``` coffee
'atom-workspace atom-text-editor':
  'alt-up': 'editor:move-to-first-character-of-line'
  'alt-down': 'editor:move-to-end-of-line'
```
